📦 NEW: short-url to original-url
42JalS/url-shortener pull request #17
Opened 2021-11-23 14:17 UTC by sangcp

short-url to original-url

2021-11-24 04:47 UTC, srngch requested changes
단어 수정해주세요
- `longUrl` -> `OriginalUrl`
- `OriginUrl` -> `OriginalUrl`
- `ShortUrl` -> `ConvertedUrl`

2021-11-24 04:47 UTC, srngch commented on controllers/urls.controller.js
> +};
이 부분 파일로 분리해주세요..!
`urls.original.controller.js`로 생성해주시면 됩니다

2021-11-24 04:48 UTC, chaejin-jen commented on routes/index.js
> +router.get('/original-url/:shortUrl', controller.changeShortUrlToOriginUrl);
요 부분 route parameters 말고 query string 으로 하자는 의견이 있었습니다!
req.query.originalURL 이런식으로 하면 될것 같구
이후에 다시 같이 짚어봐요!

그리고 converted 로 바꿔야하는건가 싶네요!

2021-11-24 04:48 UTC, chaejin-jen commented on controllers/urls.controller.js
> +exports.changeShortUrlToOriginUrl = async (req, res, next) => {
이 부분 converted로 바꿔야 하는건가요?

2021-11-24 04:56 UTC, m1nje requested changes

2021-11-24 04:56 UTC, m1nje commented on routes/index.js
> +const controller = require('../controllers/urls.controller');
아래에 urlsController 있는 데 추가하셔서 이 부분은 수정 필요할 것 같아요

2021-11-25 04:20 UTC, EeeUnS approved these changes

2021-11-25 04:21 UTC, EeeUnS commented
public 쪽 코드가 조금 바뀌어서 이 부분 나중에 폼 합칠때 고려해야할것같아욥 일단은 머지!

2021-11-25 04:26 UTC, m1nje commented on routes/index.js
> +const OriginalController = require('../controllers/urls.original.controller')
O → o

2021-11-25 04:26 UTC, m1nje approved these changes

2021-11-25 04:33 UTC, chaejin-jen approved these changes

2021-11-25 04:45 UTC, srngch reviewed
변수명 대소문자 수정 필요

2021-11-25 04:45 UTC, srngch commented on routes/index.js
> +const OriginalController = require('../controllers/urls.original.controller')
```suggestion
const originalController = require('../controllers/urls.original.controller')
```

2021-11-25 04:45 UTC, srngch commented on routes/index.js
> +router.get('/original-url/:convertedUrl', OriginalController.changeConvertedUrlToOriginalUrl);
```suggestion
router.get('/original-url/:convertedUrl', originalController.changeConvertedUrlToOriginalUrl);
```

2021-11-25 04:46 UTC, srngch approved these changes

2021-11-25 04:47 UTC, merged